Hotel/urls.py
from django.urls import path
from .views import habitaciones, home, ubicacion, exit, login, contacto, eventos, registro
urlpatterns = [
    path('', home, name='home'),
    path('habitaciones/', habitaciones, name='habitaciones'),
    path('ubicacion/', ubicacion, name='ubicacion'),
    path("logout/", exit, name="exit"),
    path('login/', login, name='login'),
    path('contacto/', contacto, name='contacto'),
    path('eventos/', eventos, name='eventos'),
    path('registro/', registro, name="registro"),
]  
 

HotelZafiro/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
#from django.contrib.auth.views import login, logout_then_login


urlpatterns = [
    path('', include('Hotel.urls')),
    path('', include('reservacion.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

]
#urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservacion/urls.py
from django.urls import path
from .views import reserva, metodo
app_name = 'reservacion'  # Este es el espacio de nombres

urlpatterns = [
    path('reserva/', reserva, name='reserva'),
    path('metodo/', metodo, name='metodo'),
]  

reservacion/models.py
from django.db import models
from Hotel.models import Habitaciones, Huespedes
from django.contrib.auth.models import User
# Create your models here.



class Reservaciones(models.Model):
    idreserva = models.AutoField(db_column='IdReserva', primary_key=True)  # Field name made lowercase.
    fechaentrada = models.DateField(db_column='FechaEntrada')  # Field name made lowercase.
    fechasalida = models.DateField(db_column='FechaSalida')  # Field name made lowercase.
    iva = models.DecimalField(max_digits=5, decimal_places=2,  default=0.00)
    cantidadpersona = models.PositiveIntegerField()
    estado = models.BooleanField(default=True, verbose_name= "Estado")
    idhabitacion = models.ForeignKey(Habitaciones, models.DO_NOTHING, db_column='IdHabitacion', blank=True, null=True)  # Field name made lowercase.
    idusuario = models.ForeignKey(User, models.DO_NOTHING, db_column='idUsuario', blank=True, null=True)  # Field name made lowercase.
    idhuesped = models.ForeignKey(Huespedes, models.DO_NOTHING, db_column='idHuesped', blank=True, null=True)
  # Field name made lowercase.

    class Meta:
        managed = True
        db_table = 'reservaciones'
    def __str__(self):
        return f'reserva de habitacion {self.idhabitacion} por {self.idhuesped}'

reservacion/forms.py
from django import forms
from .models import Reservaciones, Huespedes

class ReservacionesForm(forms.ModelForm):
    # Agregar campos para el huésped
    dni = forms.IntegerField(label='Dni',),
    nombre = forms.CharField(label='Nombre', max_length=30)
    apellido = forms.CharField(label='Apellido', max_length=40)
    direccion = forms.CharField(label='Dirección', max_length=100)
    telefono = forms.CharField(label='Teléfono', max_length=20)
    email = forms.CharField(label='Email', max_length=250)

    class Meta:
        model = Reservaciones
        fields = ['fechaentrada', 'fechasalida', 'cantidadpersona']
       
    # Personalizar widgets o validaciones específicas para cada campo
    nombre = forms.CharField(label='Nombre', max_length=30, widget=forms.TextInput(attrs={'class': 'input', 'type': 'text', 'required': True}))
    apellido = forms.CharField(label='Apellido', max_length=40, widget=forms.TextInput(attrs={'class': 'input', 'type': 'text', 'required': True}))
    fechaentrada = forms.DateField(
    label='Fecha de Entrada',
    widget=forms.DateInput(attrs={'type': 'date', 'id': 'llegada', 'name': 'fecha-llegada', 'class': 'input'}),
    required=True),
    fechasalida = forms.DateField(label='Fecha de Salida', widget=forms.DateInput(attrs={'type': 'date', 'id':'salida', 'name':'fecha-salida', 'class':'input','required': True})),
    cantidad_persona = forms.ChoiceField(
        label='Cantidad de Personas',
        choices=[('', 'Selecciona una opción'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')],
        required=True,
        widget=forms.Select(attrs={'class': 'opciones', 'required': True})
    )
    def clean(self):
        cleaned_data = super().clean()

        # Validar lógica personalizada si es necesario
        fechaentrada = cleaned_data.get('fechaentrada')
        fechasalida = cleaned_data.get('fechasalida')

        if fechaentrada and fechasalida and fechaentrada >= fechasalida:
            raise forms.ValidationError('La fecha de salida debe ser posterior a la fecha de entrada.')

        return cleaned_data

reservacion/views.py
from django.shortcuts import render, redirect
from .forms import ReservacionesForm
from .models import Huespedes
def metodo(request):
    return render(request, 'reservacion/metodo.html')


def reserva(request):
    data = {
        "form": ReservacionesForm()
    }

    if request.method == "POST":
        reserva_form = ReservacionesForm(request.POST)
        if reserva_form.is_valid():
            print("es valido")
            # Procesar y guardar los datos del formulario
            reserva = reserva_form.save(commit=False)
            # Crear un nuevo huésped con los datos del formulario
            huesped = Huespedes(
                dni=reserva_form.cleaned_data["dni"],
                nombre=reserva_form.cleaned_data['nombre'],
                apellido=reserva_form.cleaned_data['apellido'],
                direccion=reserva_form.cleaned_data['direccion'],
                telefono=reserva_form.cleaned_data['telefono'],
                email=reserva_form.cleaned_data['email']
            )
            huesped.save()

            # Asociar el huésped con la reserva
            reserva.idhuesped = huesped
            reserva.save()

            data["mensaje"] = "Reserva enviada"
            return redirect('reservacion:metodo')

            #return redirect('metodo')  # Redirigir a una página de confirmación o a donde sea necesario

        else:
            data["form"] = reserva_form

    return render(metodo, data)

reservacion/templates/reservacion/metodo.html
<h1>metodo</h1>

reservacion/templates/reservacion/reserva.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/reserva.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Document</title>
</head>

<body>

    <section class="reserva" id="reserva">
        <div class="img"></div>
        <div class="contenedor-reserva">

            <div class="reservar-contenedor">
                {% if request.user.is_authenticated %}
                <h3>
                    BIENVENIDO {{ request.user.username|upper }}
                </h3>
                {% endif %}
                <h1>Reservar</h1>
                <form action="{% url 'reservacion:reserva' %}" method="post">
                    {% csrf_token %}
                    <div class="nombre-apellido">
                        <h2>Nombre y Apellido</h2>
                        <div class="c-nombre">
                            <div class="input-form">
                                {{ form.nombre }}
                                <label class="textUser">Nombre</label>
                            </div>
                            <div class="input-form">
                                {{ form.apellido }}
                                <label class="textUser">Apellido</label>
                            </div>
                            
                        </div> 
                    </div>


                    <div class="tipo-habitacion">
                        <h2>Tipo de habitacion</h2>
                        <div class="container">
                                <label>
                                    <input type="radio" name="radio" value="{{ habitacion_individual.id }}" checked="">
                                    <span>Individual</span>
                                </label>
                                <label>
                                    <input type="radio" name="radio" value="{{ habitacion_doble.id }}">
                                    <span>Doble</span>
                                </label>
                                <label>
                                    <input type="radio" name="radio" value="{{ habitacion_familiar.id }}">
                                    <span>Familiar</span>
                                </label>  
                        </div>
                    </div>


                    <div class="cant-personas">
                        <h2>Cantidad de Personas</h2>

                        <div class="opciones">
                            {{ form.cantidad_persona }}
                        </div>
                    </div>



                    <div class="fecha-llegada-salida">
                        <h2>Fecha de Llegada y Salida</h2>
                        <div class="c-fls">
                            <div class="input-form">
                                <label class="textDate">Llegada</label>
                                {{ form.fechaentrada }}
                           </div>

                            <div class="input-form">
                                <label class="textDate" >Salida</label>
                                {{ form.fechasalida }}
                            </div>
                        </div>
                    </div>
                    <!--<button type="submit">
                        <span>Siguiente</span>
                        <svg width="34" height="34" viewBox="0 0 74 74" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <circle cx="37" cy="37" r="35.5" stroke="black" stroke-width="3"></circle>
                            <path d="M25 35.5C24.1716 35.5 23.5 36.1716 23.5 37C23.5 37.8284 24.1716 38.5 25 38.5V35.5ZM49.0607 38.0607C49.6464 37.4749 49.6464 36.5251 49.0607 35.9393L39.5147 26.3934C38.9289 25.8076 37.9792 25.8076 37.3934 26.3934C36.8076 26.9792 36.8076 27.9289 37.3934 28.5147L45.8787 37L37.3934 45.4853C36.8076 46.0711 36.8076 47.0208 37.3934 47.6066C37.9792 48.1924 38.9289 48.1924 39.5147 47.6066L49.0607 38.0607ZM25 38.5L48 38.5V35.5L25 35.5V38.5Z" fill="black"></path>
                        </svg>
                    </button> -->
                    <button type="submit" name="submit">Enviar Reserva</button>

                    {% if mensaje %}
                        <p>{{ mensaje }}</p>
                    {% endif %}
                </form>
                
            </div>

        </div>
    </section>
</body>

</html>




<!-- <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enviar Reserva</button>
</form>

{% if mensaje %}
    <p>{{ mensaje }}</p>
{% endif %}  
 -->